// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "db": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/freddygv/cassandra-wannabe/api/design
// --out=$(GOPATH)/src/github.com/freddygv/cassandra-wannabe
// --version=v1.3.1

package app

import (
	"github.com/goadesign/goa"
)

// A movie rating by a user (default view)
//
// Identifier: application/cassandra.wannabe.rating+json; view=default
type Rating struct {
	MovieID int     `form:"movieId" json:"movieId" xml:"movieId"`
	Rating  float64 `form:"rating" json:"rating" xml:"rating"`
	UserID  int     `form:"userId" json:"userId" xml:"userId"`
}

// Validate validates the Rating media type instance.
func (mt *Rating) Validate() (err error) {

	if mt.MovieID < 1 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`response.movieId`, mt.MovieID, 1, true))
	}
	if mt.Rating < 0.500000 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`response.rating`, mt.Rating, 0.500000, true))
	}
	if mt.Rating > 5.000000 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`response.rating`, mt.Rating, 5.000000, false))
	}
	if mt.UserID < 1 {
		err = goa.MergeErrors(err, goa.InvalidRangeError(`response.userId`, mt.UserID, 1, true))
	}
	return
}
