// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "db": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/freddygv/cassandra-wannabe/api/design
// --out=$(GOPATH)/src/github.com/freddygv/cassandra-wannabe/api
// --version=v1.3.1

package app
